# Generated by Django 3.2.5 on 2021-07-01 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_type', models.TextField()),
                ('breed', models.TextField()),
                ('story', models.TextField()),
                ('days_in_our_care', models.TextField()),
                ('health', models.TextField()),
                ('gender', models.TextField()),
                ('age', models.TextField()),
            ],
        ),
    ]
